name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your default branch is master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./  # change if your site is in 'dist' or 'build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
